### ISSUE TITLE
consider referencing "almost ready" feature of using MI to pull from ACR directly

### ISSUE THREAD

**Issue by aflinchb** [retaildevcrews/app-service-managed-identity-key-vault-csharp#9]
It is now possible to have a Linux containerized web app in App Service access images from ACR using managed identity.  However, the feature does not appear to be fully supported/integrated yet and is confusing to get working (although, it does work). 

See long thread here describing the current buggy behavior: https://github.com/MicrosoftDocs/azure-docs/issues/64660

**Comment by bartr** [comment]
the implementation is pretty clean and working consistently
